spring: 
   application: 
        name: spring-boot-file-upload
   servlet: 
        multipart: 
            enabled: true
            max-file-size: 150MB
            max-request-size: 200MB
file: 
   upload-dir: ./uploads
